version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: whatsapp-drive-assistant
    ports:
      - "5678:5678"
    environment:
      # n8n Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin@localhost.com
      - N8N_BASIC_AUTH_PASSWORD=Admin123
      - WEBHOOK_URL=http://localhost:5678
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      
      # Database Configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      
      # Redis Configuration (for queue management)
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
      
      # Security
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-32-character-encryption-key}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      
      # Performance
      - N8N_LOG_LEVEL=info
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      
      # External Services (from .env file)
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONFIRMATION_KEYWORD=${CONFIRMATION_KEYWORD:-CONFIRM}
      - AUDIT_SPREADSHEET_ID=${AUDIT_SPREADSHEET_ID}
    
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflow.json:/tmp/workflow.json:ro
      - ./scripts:/scripts:ro
    
    depends_on:
      - postgres
      - redis
    
    restart: unless-stopped
    
    networks:
      - n8n-network

  postgres:
    image: postgres:15-alpine
    container_name: n8n-postgres
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - n8n-network

  redis:
    image: redis:7-alpine
    container_name: n8n-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - n8n-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: n8n-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - n8n
    restart: unless-stopped
    networks:
      - n8n-network
    profiles:
      - production

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  n8n-network:
    driver: bridge 